////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2017 Flax Engine. All rights reserved.
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine.Rendering
{
	/// <summary>
	/// Allows to perform custom rendering to texture.
	/// </summary>
	public partial class RenderTarget : Object
	{
		/// <summary>
		/// Gets texture surface format.
		/// </summary>
		[UnmanagedCall]
		public PixelFormat Format
		{
#if UNIT_TEST_COMPILANT
			get; set;
#else
			get { return Internal_GetFormat(unmanagedPtr); }
#endif
		}

#region Internal Calls
#if !UNIT_TEST_COMPILANT
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern PixelFormat Internal_GetFormat(IntPtr obj);
#endif
#endregion
	}
}

