////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2017 Flax Engine. All rights reserved.
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
	/// <summary>
	/// Provides the ability to create, configure, show, and manage the lifetime of windows.
	/// </summary>
	public partial class Window : Object
	{
		/// <summary>
		/// Gets a value that indicates whether a window is in a fullscreen mode.
		/// </summary>
		[UnmanagedCall]
		public bool IsFullscreen
		{
#if UNIT_TEST_COMPILANT
			get; set;
#else
			get { return Internal_GetIsFullscreen(unmanagedPtr); }
#endif
		}

#region Internal Calls
#if !UNIT_TEST_COMPILANT
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool Internal_GetIsFullscreen(IntPtr obj);
#endif
#endregion
	}
}

