////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2017 Flax Engine. All rights reserved.
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
	/// <summary>
	/// Contains IES profile texture used by the lights to simulate real life bulb light emission.
	/// </summary>
	public partial class IESProfile : BinaryAsset
	{
		/// <summary>
		/// Creates new <see cref="IESProfile"/> object.
		/// </summary>
		private IESProfile() : base()
		{
		}

		/// <summary>
		/// Gets the total mip levels count of the texture. Actual resident mipmaps count may be different due to dynamic content streaming.
		/// </summary>
		[UnmanagedCall]
		public int MipLevels
		{
#if UNIT_TEST_COMPILANT
			get; set;
#else
			get { return Internal_GetMipLevels(unmanagedPtr); }
#endif
		}

		/// <summary>
		/// Gets the current mip levels count of the texture that are on GPU ready to use.
		/// </summary>
		[UnmanagedCall]
		public int ResidentMipLevels
		{
#if UNIT_TEST_COMPILANT
			get; set;
#else
			get { return Internal_GetResidentMipLevels(unmanagedPtr); }
#endif
		}

#region Internal Calls
#if !UNIT_TEST_COMPILANT
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int Internal_GetMipLevels(IntPtr obj);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int Internal_GetResidentMipLevels(IntPtr obj);
#endif
#endregion
	}
}

