////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2017 Flax Engine. All rights reserved.
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
	/// <summary>
	/// Model asset that contains model object made of meshes which can rendered on the GPU.
	/// </summary>
	public sealed partial class Model : BinaryAsset
	{
		/// <summary>
		/// Creates new <see cref="Model"/> object.
		/// </summary>
		private Model() : base()
		{
		}

		/// <summary>
		/// Gets amount of loaded model LODs.
		/// </summary>
		[UnmanagedCall]
		public int LoadedLODs
		{
#if UNIT_TEST_COMPILANT
			get; set;
#else
			get { return Internal_GetLoadedLODs(unmanagedPtr); }
#endif
		}

#region Internal Calls
#if !UNIT_TEST_COMPILANT
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int Internal_GetLoadedLODs(IntPtr obj);
#endif
#endregion
	}
}

