// Copyright (c) 2012-2019 Wojciech Figat. All rights reserved.
// This code was generated by a tool. Changes to this file may cause
// incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
    /// <summary>
    /// Particle system contains a composition of particle emitters and playback information.
    /// </summary>
    public sealed partial class ParticleSystem : BinaryAsset
    {
        /// <summary>
        /// Creates new <see cref="ParticleSystem"/> object.
        /// </summary>
        private ParticleSystem() : base()
        {
        }

        /// <summary>
        /// Initializes the particle system that plays a given particles emitter.
        /// </summary>
        /// <param name="emitter">...</param>
        /// <param name="duration">...</param>
        /// <param name="loop">...</param>
#if UNIT_TEST_COMPILANT
        [Obsolete("Unit tests, don't support methods calls.")]
#endif
        [UnmanagedCall]
        public void Init(ParticleEmitter emitter, float duration, bool loop)
        {
#if UNIT_TEST_COMPILANT
            throw new NotImplementedException("Unit tests, don't support methods calls. Only properties can be get or set.");
#else
            Internal_Init(unmanagedPtr, Object.GetUnmanagedPtr(emitter), duration, loop);
#endif
        }

        #region Internal Calls

#if !UNIT_TEST_COMPILANT
        [MethodImpl(MethodImplOptions.InternalCall)]
        internal static extern void Internal_Init(IntPtr obj, IntPtr emitter, float duration, bool loop);
#endif

        #endregion
    }
}
