// Copyright (c) 2012-2018 Wojciech Figat. All rights reserved.
// This code was generated by a tool. Changes to this file may cause
// incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
    /// <summary>
    /// Raw bytes container asset.
    /// </summary>
    public sealed partial class RawDataAsset : BinaryAsset
    {
        /// <summary>
        /// Creates new <see cref="RawDataAsset"/> object.
        /// </summary>
        private RawDataAsset() : base()
        {
        }

        /// <summary>
        /// Gets the bytes array stored by this data container asset.
        /// </summary>
        /// <returns>The loaded bytes.</returns>
#if UNIT_TEST_COMPILANT
        [Obsolete("Unit tests, don't support methods calls.")]
#endif
        [UnmanagedCall]
        public byte[] GetData()
        {
#if UNIT_TEST_COMPILANT
            throw new NotImplementedException("Unit tests, don't support methods calls. Only properties can be get or set.");
#else
            return Internal_GetData(unmanagedPtr);
#endif
        }

        #region Internal Calls

#if !UNIT_TEST_COMPILANT
        [MethodImpl(MethodImplOptions.InternalCall)]
        internal static extern byte[] Internal_GetData(IntPtr obj);
#endif

        #endregion
    }
}
