////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2017 Flax Engine. All rights reserved.
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
	/// <summary>
	/// Empty actor is usefull to create hierarchy and/or hold scripts. See <see cref="Script"/>.
	/// </summary>
	public sealed partial class EmptyActor : Actor
	{
		/// <summary>
		/// Creates new <see cref="EmptyActor"/> object.
		/// </summary>
		public EmptyActor() : base()
		{
		}

#region Internal Calls
#if !UNIT_TEST_COMPILANT
#endif
#endregion
	}
}

