// Copyright (c) 2012-2018 Wojciech Figat. All rights reserved.
// This code was generated by a tool. Changes to this file may cause
// incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
    /// <summary>
    /// Contains a single GUI control.
    /// </summary>
    [Serializable]
    public sealed partial class UIControl : Actor
    {
        /// <summary>
        /// Creates new <see cref="UIControl"/> object.
        /// </summary>
        private UIControl() : base()
        {
        }

        /// <summary>
        /// Creates new instance of <see cref="UIControl"/> object.
        /// </summary>
        /// <returns>Created object.</returns>
#if UNIT_TEST_COMPILANT
        [Obsolete("Unit tests, don't support methods calls.")]
#endif
        [UnmanagedCall]
        public static UIControl New()
        {
#if UNIT_TEST_COMPILANT
            throw new NotImplementedException("Unit tests, don't support methods calls. Only properties can be get or set.");
#else
            return Internal_Create(typeof(UIControl)) as UIControl;
#endif
        }

        #region Internal Calls

#if !UNIT_TEST_COMPILANT
#endif

        #endregion
    }
}
