// Copyright (c) 2012-2020 Wojciech Figat. All rights reserved.
// This code was generated by a tool. Changes to this file may cause
// incorrect behavior and will be lost if the code is regenerated.

using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
    /// <summary>
    /// Texture resource that contains an atlas of cached font glyphs.
    /// </summary>
    public partial class FontTextureAtlas : Texture
    {
        /// <summary>
        /// Creates new <see cref="FontTextureAtlas"/> object.
        /// </summary>
        private FontTextureAtlas() : base()
        {
        }

        #region Internal Calls

#if !UNIT_TEST_COMPILANT
#endif

        #endregion
    }
}
