////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2017 Flax Engine. All rights reserved.
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{

	/// <summary>
	/// The scene manager handles the scenes collection and spawns/deleted actors.
	/// </summary>
	public static partial class SceneManager
	{
		/// <summary>
		/// Gets array of the loaded scenes.
		/// </summary>
		[UnmanagedCall]
		public static Scene[] Scenes
		{
#if UNIT_TEST_COMPILANT
			get; set;
#else
			get { return Internal_GetScenes(); }
#endif
		}

		/// <summary>
		/// Tries to find actor with given ID.
		/// </summary>
		/// <param name="id">The actor id.</param>
		/// <returns>Found actor or null if cannot find it.</returns>
#if UNIT_TEST_COMPILANT
		[Obsolete("Unit tests, don't support methods calls.")]
#endif
		[UnmanagedCall]
		public static Actor FindActor(Guid id) 
		{
#if UNIT_TEST_COMPILANT
			throw new NotImplementedException("Unit tests, don't support methods calls. Only properties can be get or set.");
#else
			return Internal_FindActorById(ref id);
#endif
		}

		/// <summary>
		/// Tries to find actor with given name.
		/// </summary>
		/// <param name="name">The actor name.</param>
		/// <returns>Found actor or null if cannot find it.</returns>
#if UNIT_TEST_COMPILANT
		[Obsolete("Unit tests, don't support methods calls.")]
#endif
		[UnmanagedCall]
		public static Actor FindActor(string name) 
		{
#if UNIT_TEST_COMPILANT
			throw new NotImplementedException("Unit tests, don't support methods calls. Only properties can be get or set.");
#else
			return Internal_FindActorByName(name);
#endif
		}

		/// <summary>
		/// Tries to find scene with given ID (checks only loaded scenes, see Scenes).
		/// </summary>
		/// <param name="id">The scene id.</param>
		/// <returns>Found scene or null if cannot find it (it's not loaded).</returns>
#if UNIT_TEST_COMPILANT
		[Obsolete("Unit tests, don't support methods calls.")]
#endif
		[UnmanagedCall]
		public static Scene FindScene(Guid id) 
		{
#if UNIT_TEST_COMPILANT
			throw new NotImplementedException("Unit tests, don't support methods calls. Only properties can be get or set.");
#else
			return Internal_FindScene(ref id);
#endif
		}

#region Internal Calls
#if !UNIT_TEST_COMPILANT
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern Scene[] Internal_GetScenes();
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern Actor Internal_FindActorById(ref Guid id);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern Actor Internal_FindActorByName(string name);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern Scene Internal_FindScene(ref Guid id);
#endif
#endregion
	}
}

