////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2017 Flax Engine. All rights reserved.
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
	/// <summary>
	/// The interface to get time information from Flax.
	/// </summary>
	public static partial class Time
	{
		/// <summary>
		/// Gets or sets scale at which the time is passing. This can be used for slow motion effects.
		/// </summary>
		[UnmanagedCall]
		public static float TimeScale
		{
#if UNIT_TEST_COMPILANT
			get; set;
#else
			get { return Internal_GetTimeScale(); }
			set { Internal_SetTimeScale(value); }
#endif
		}
        
#region Internal Calls
#if !UNIT_TEST_COMPILANT
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float Internal_GetTimeScale();
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Internal_SetTimeScale(float val);
#endif
#endregion
	}
}

