// Copyright (c) 2012-2018 Wojciech Figat. All rights reserved.
// This code was generated by a tool. Changes to this file may cause
// incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.CompilerServices;

namespace FlaxEngine
{
    /// <summary>
    /// Cube texture asset contains 6 images that is usually stored on a GPU as a cube map (one slice per each axis direction).
    /// </summary>
    public partial class CubeTexture : TextureBase
    {
        /// <summary>
        /// Creates new <see cref="CubeTexture"/> object.
        /// </summary>
        private CubeTexture() : base()
        {
        }

        #region Internal Calls

#if !UNIT_TEST_COMPILANT
#endif

        #endregion
    }
}
